openapi: 3.0.0
info:
  title: Quanto Falta
  description: API do aplicativo Quanto Falta feita em Node.Js utilizando MongoDB
  version: 1.0.1
servers:
  - url: http://localhost:4000/api/
    description: Desenvolvimento local
  - url: https://quanto-falta.onrender.com/api/
    description: Servidor em Nuvem RENDER
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: auth-token

  schemas:   
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        pwd:
          type: string
        date:
          type: string

paths:

  /users/register:
    post:
      summary: Registro de novo usuário
      description: Registro de novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        201:
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  _id:
                    type: string

  /users/login:
    post:
      summary: Login de Usuário
      description: Login para pegar o JWT (Token de autenticação e acesso ao aplicativo)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                pwd:
                  type: string
      
      responses:
        200:
          description: Usuário Logado com Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: string